# Generated by Django 5.0.6 on 2024-08-05 19:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to='posts/'),
        ),
    ]
