# Generated by Django 5.0.6 on 2024-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_post_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
