# Generated by Django 5.0.6 on 2024-07-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_remove_friendrequest_accepted_remove_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='diary.profile'),
        ),
    ]
