# Generated by Django 5.0.6 on 2024-07-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
